services:
  postgres:
    image: 'postgres:alpine3.19'
    container_name: 'postgres3'
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - './sql/init.sql:/docker-entrypoint-initdb.d/1.sql'
